changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot

  categories:
    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Features
      labels:
        - enhancement
        - feature

    - title: Fixes
      labels:
        - bug
        - fix

    - title: Documentation
      labels:
        - documentation

    - title: Security
      labels:
        - security

    - title: Dependencies
      labels:
        - dependencies

    - title: Other Changes
      labels:
        - "*"
