name: Terraform Validate

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/terraform-validate.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"
      - run: terraform fmt -check -recursive
